#!/usr/bin/env python3
"""
直接解析原始 .onnx 文件的 protobuf 结构，递归遍历所有节点（包括 If/Loop/Scan
这类控制流算子内部的子图），把图里出现过的每一个 (domain, op_type) 都提取出来，
跟 convert_onnx_models_to_ort.py 生成的清单取并集、合并进 required_operators.config。

背景：convert_onnx_models_to_ort.py 是"先做图优化、再扫描优化后的图"，这样能
覆盖 Conv+Relu 融合成 FusedConv 这类运行时才出现的算子，但依赖图优化器的具体
行为，出现过实测缺算子（Relu/HardSigmoid/Div 陆续报过"找不到实现"）、具体是
优化的哪个环节导致遗漏没有100%查清楚。这个脚本换一个思路：不依赖任何优化，直接
从原始文件里"字面意义上出现过的每个算子"做穷举，作为兜底——两种方法各有側重
（一个能覆盖运行时融合出的算子，一个能保证原始文件里写的算子一个不漏），取并集
理论上比单独任何一种方法更完整，能从根源上避免"一次只报一个缺失算子、改完一个
下次又冒出下一个"这种来回拉锯。

用法：python3 extract_raw_ops.py <required_operators.config的路径> <模型目录（递归找.onnx）>
"""

import sys
import re
from pathlib import Path

import onnx


def collect_ops_from_graph(graph, ops_by_opset, opset_by_domain):
    """递归遍历一个 GraphProto，把用到的每个 (domain, op_type) 记进 ops_by_opset。"""
    for node in graph.node:
        domain = node.domain if node.domain else "ai.onnx"
        opset = opset_by_domain.get(domain, opset_by_domain.get("", 1))
        ops_by_opset.setdefault((domain, opset), set()).add(node.op_type)
        # If/Loop/Scan 这类控制流算子，实际计算逻辑在属性里的子图（GraphProto）
        # 里，子图里的节点也要递归扫描，不然会漏掉分支/循环体内部用到的算子。
        for attr in node.attribute:
            if attr.type == onnx.AttributeProto.GRAPH:
                collect_ops_from_graph(attr.g, ops_by_opset, opset_by_domain)
            elif attr.type == onnx.AttributeProto.GRAPHS:
                for g in attr.graphs:
                    collect_ops_from_graph(g, ops_by_opset, opset_by_domain)


def extract_ops(onnx_path):
    model = onnx.load(str(onnx_path), load_external_data=False)
    opset_by_domain = {}
    for opset in model.opset_import:
        # 空字符串 domain 就是标准的 ai.onnx 域
        opset_by_domain[opset.domain] = opset.version
    ops_by_opset = {}
    collect_ops_from_graph(model.graph, ops_by_opset, opset_by_domain)
    return ops_by_opset


LINE_PATTERN = re.compile(r"^([\w.]+);([\d,]+);(.+)$")


def merge_into_config(config_path, all_ops_by_opset):
    with open(config_path, encoding="utf-8") as f:
        lines = f.readlines()

    # 先解析已有配置文件里每个 (domain, opset) 已经包含的算子（跳过带类型信息、
    # 含"{"的行，避免破坏 JSON 类型标注格式，这些行原样保留）。
    existing = {}
    passthrough_lines = []
    for line in lines:
        stripped = line.rstrip("\n")
        m = LINE_PATTERN.match(stripped)
        if m and "{" not in m.group(3):
            domain, opset_str, ops_str = m.groups()
            # opset 字段可能是逗号分隔的多个版本号，这里只取第一个作为合并 key，
            # 跟下面新提取的算子按 (domain, 单个opset数字) 对齐。
            for opset_num in opset_str.split(","):
                key = (domain, int(opset_num))
                existing.setdefault(key, set()).update(
                    op.strip() for op in ops_str.split(",") if op.strip()
                )
        elif stripped and not stripped.startswith("#"):
            passthrough_lines.append(stripped)

    # 合并：原始文件直接扫描出来的算子，全部并入对应 (domain, opset)。
    merged = {k: set(v) for k, v in existing.items()}
    added_any = False
    for (domain, opset), ops in all_ops_by_opset.items():
        key = (domain, opset)
        before = merged.get(key, set())
        after = before | ops
        if after != before:
            added_any = True
        merged[key] = after

    out_lines = ["# Generated by convert_onnx_models_to_ort.py, merged with extract_raw_ops.py\n"]
    for (domain, opset), ops in sorted(merged.items()):
        out_lines.append(f"{domain};{opset};{','.join(sorted(ops))}\n")
    for line in passthrough_lines:
        out_lines.append(line + "\n")

    with open(config_path, "w", encoding="utf-8") as f:
        f.writelines(out_lines)

    return added_any, out_lines


def main():
    if len(sys.argv) != 3:
        print("用法: python3 extract_raw_ops.py <required_operators.config的路径> <模型目录>", file=sys.stderr)
        sys.exit(2)

    config_path = sys.argv[1]
    models_dir = Path(sys.argv[2])

    onnx_files = list(models_dir.rglob("*.onnx"))
    if not onnx_files:
        print(f"❌ 在 {models_dir} 下没找到任何 .onnx 文件", file=sys.stderr)
        sys.exit(1)

    all_ops_by_opset = {}
    for f in onnx_files:
        print(f"扫描: {f}")
        ops = extract_ops(f)
        for key, op_set in ops.items():
            all_ops_by_opset.setdefault(key, set()).update(op_set)
            print(f"  {key}: {sorted(op_set)}")

    added_any, out_lines = merge_into_config(config_path, all_ops_by_opset)

    print(f"\n{'✅ 补充了原始文件里扫描到但清单里没有的算子' if added_any else 'ℹ️ 原始文件扫描结果跟已有清单完全一致，未作改动'}")
    print("--- 合并后的完整清单 ---")
    print("".join(out_lines))


if __name__ == "__main__":
    main()
