name: Build OpenCV.js


on:

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:


    - uses: actions/checkout@v4


    - name: install

      run:

        sudo apt update

        sudo apt install -y cmake python3 build-essential



    - name: emsdk

      run: |

        git clone https://github.com/emscripten-core/emsdk.git

        cd emsdk

        ./emsdk install latest

        ./emsdk activate latest



    - name: opencv

      run: |

        git clone \
        --depth 1 \
        --branch 4.12.0 \
        https://github.com/opencv/opencv.git



    - name: build

      shell: bash

      run: |

        source emsdk/emsdk_env.sh


        python3 opencv/platforms/js/build_js.py \
        build_output \
        --build_wasm \
        --disable_single_file \
        --config "$(pwd)/opencv_js_minimal.config.py" \
        --cmake_option="-DBUILD_TESTS=OFF" \
        --cmake_option="-DBUILD_PERF_TESTS=OFF" \
        --cmake_option="-DBUILD_EXAMPLES=OFF"



    - name: verify

      run: |

        node verify_opencv_build.js \
        build_output/bin/opencv.js



    - uses: actions/upload-artifact@v4

      with:

        name: opencv-js

        path:

          build_output/bin/opencv.js

          build_output/bin/opencv_js.wasm
